C_PADDING_SIZE = 30
APP_WIDTH = 300
APP_HEIGHT = 400
CREATE_TXT = 'Create'
HOME_TXT = 'Home'
HOME_MESSAGE = 'Babyrobot Deployment Tool'
NEW_PROJECT_TEXT = 'New Project'
PROJECT_TXT = 'Project'
DEPLOY_TXT = 'Deploy'
PROJECT_NAME_TXT = 'Project Name'
PROJECT_IP_TXT = 'Project IP'
PROJECT_USERNAME_TXT = 'Username'
